name: 'Rsync Deployments Action'
description: 'GitHub Action for deploying code via rsync over ssh securely - used by 5k+ workflows!'
author: 'Burnett01'
inputs:
  switches:
    description: 'The switches'
    required: true
  rsh:
    description: 'The remote shell argument'
    required: false
    default: ''
  legacy_allow_rsa_hostkeys:
    description: 'Enables support for legacy RSA host keys on OpenSSH 8.8+'
    required: false
    default: 'false'
  strict_hostkeys_checking:
    description: 'Controls strict host keys checking'
    required: false
    default: 'false'
  path:
    description: 'The local path'
    required: false
    default: ''
  remote_path:
    description: 'The remote path'
    required: true
  remote_host:
    description: 'The remote host'
    required: true
  remote_port:
    description: 'The remote port'
    required: false
    default: 22
  remote_user:
    description: 'The remote user'
    required: true
  remote_key:
    description: 'The remote key'
    required: true
  remote_key_pass:
    description: 'The remote key passphrase'
    required: false
    default: ''
  debug:
    description: 'Debug the action'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'send'  
  color: 'gray-dark'
