#!/bin/sh

source agent-start
cat /dev/stdin | sed 's/-----BEGIN RSA PRIVATE KEY----- /-START-/' | sed 's/-----END RSA PRIVATE KEY----- /-END-/' |
	tr ' ' '\n' | sed 's/-START-/-----BEGIN RSA PRIVATE KEY-----\n/' | sed 's/-END-/-----END RSA PRIVATE KEY-----\n/' |
	ssh-add -