#!/bin/sh

agent-start
echo /dev/stdin | sed 's/-----BEGIN RSA PRIVATE KEY-----/-START-/' | sed 's/-----END RSA PRIVATE KEY-----/-END-/' |
	tr ' ' '\n' | sed 's/-START-/-----BEGIN RSA PRIVATE KEY-----/' | sed 's/-END-/-----END RSA PRIVATE KEY-----/' |
	ssh-add -